### ISSUE TITLE
[Android] io.flutter.plugin.common.PluginRegistry.Registrar deprecated in Flutter 3.29.0

### ISSUE THREAD

**Issue by lesterbotello** [bugsee/flutter-bugsee#19]
Hello Team!

It looks like apps using the `flutter-bugsee` package are failing to build on Android on Flutter version 3.29.0, because it's using the deprecated plugin Flutter APIs (more info [here](https://docs.flutter.dev/release/breaking-changes/plugin-api-migration)). Downgrading to a lower Flutter version (i.e. 3.27.1) fixes the issue.

```
C:\Users\user\AppData\Local\Pub\Cache\hosted\pub.dev\bugsee_flutter-8.4.3\android\src\main\java\com\bugsee\BugseePlugin.java:45: error: cannot find symbol
import io.flutter.plugin.common.PluginRegistry.Registrar;
                                              ^
  symbol:   class Registrar
  location: interface PluginRegistry
C:\Users\user\AppData\Local\Pub\Cache\hosted\pub.dev\bugsee_flutter-8.4.3\android\src\main\java\com\bugsee\BugseePlugin.java:141: error: cannot find symbol
    public static void registerWith(@NonNull Registrar registrar) {
                                             ^
  symbol:   class Registrar
  location: class BugseePlugin
Note: C:\Users\user\AppData\Local\Pub\Cache\hosted\pub.dev\bugsee_flutter-8.4.3\android\src\main\java\com\bugsee\BugseePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\user\AppData\Local\Pub\Cache\hosted\pub.dev\bugsee_flutter-8.4.3\android\src\main\java\com\bugsee\BugseePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':bugsee_flutter:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --info option to get more log output.
> Run with --scan to get full insights.

BUILD FAILED in 27s
Error: Gradle task assembleDebug failed with exit code 1
```

**Comment by krassx** [comment]
Hi! Thank you for pointing this out!

This is caused by the presence of an outdated integration logic (left there for compatibility reasons). Now it's time to finally remove this. We will do this ASAP.

**Comment by krassx** [comment]
We've published the new version (8.5.0) which now works with Flutter 3.29.0.

**Comment by MatFillion** [comment]
Wonderful, thanks @krassx
